name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: make check (${{ matrix.os }} • ${{ matrix.cc }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]

    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Select compiler
        shell: bash
        run: |
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
          ${{ matrix.cc }} --version

      - name: Clean
        run: make clean || true

      - name: Build & Test
        run: make check
